### ISSUE TITLE
Compatibility for Fuzs Enchanting Infuser (Fabric)

### ISSUE THREAD

**Issue by Gamemassa** [jahirxtrap/ironbookshelves#5]
Hi, this isn't entirely a duplicate of #3, because it looks like that one was for the Forge version, and I'm on Fabric 1.20.4 and still seeing the same issue. The Infuser can see the bookshelves from Iron Bookshelves, but they only increase its power by 1 instead of their modded values.

**Comment by Gamemassa** [comment]
Yup, confirmed. This is definitely fixed. Thanks!

**Comment by ThePuppeteerVT** [comment]
hi I'm experiencing this issue on fabric 1.21.1

**Comment by jahirxtrap** [comment]
@ThePuppeteerVT Fixed in 1.4.14

**Comment by ThePuppeteerVT** [comment]
awesome thank you so much!
