### ISSUE TITLE
Bronze Compatibility \\ Crafting Recipe is also mising in 1.21

### ISSUE THREAD

**Issue by makumaku1974** [jahirxtrap/ironbookshelves#6]
![Screenshot 2024-06-27 134238](https://github.com/jahirxtrap/ironbookshelves/assets/129804277/1e114e1d-d594-4248-8fd5-f209a3f41f08)

**Comment by makumaku1974** [comment]
Wait is this for the other mod called Ingotcraft?

**Comment by jahirxtrap** [comment]
It has nothing to do with ingotcraft. It should be able to use other bronze ingots, and if there aren't any, the recipe won't load. In any case, I'll check it out.

**Comment by makumaku1974** [comment]
> It has nothing to do with ingotcraft. It should be able to use other bronze ingots, and if there aren't any, the recipe won't load. In any case, I'll check it out.

No rush :>

**Comment by jahirxtrap** [comment]
I checked it, and it works as it should. The JEI issue is something visual. for the recipe to load there must be a bronze ingot from other mods.

**Comment by makumaku1974** [comment]
> I checked it, and it works as it should. The JEI issue is something visual. for the recipe to load there must be a bronze ingot from other mods.

did you used ingotcraft?

**Comment by makumaku1974** [comment]
This what happened to me tho. 
![Screenshot 2024-07-03 001805](https://github.com/jahirxtrap/ironbookshelves/assets/129804277/09972a16-be42-482d-a2a1-679d31222313)

**Comment by makumaku1974** [comment]
> I checked it, and it works as it should. The JEI issue is something visual. for the recipe to load there must be a bronze ingot from other mods.

Not really JEI, REI, nor EMI is causing this issue. It is clearly not tagging the data with a different mod recipe.
