### ISSUE TITLE
1.21.1 NeoForge Crash on world load. 

### ISSUE THREAD

**Issue by Zelioth** [jahirxtrap/ironbookshelves#8]
It appears that when Iron BookShelves is included in 1.21.1 it gives some sort of world load error. 

NeoForge 21.1.4
IronBookShelves - 1.3.4
Minecraft 1.21.1

[latest.log](https://github.com/user-attachments/files/16568491/latest.log)
[debug.log](https://github.com/user-attachments/files/16568492/debug.log)

![image](https://github.com/user-attachments/assets/91b10bbd-d513-43f4-8bee-af7e7161b799)

**Comment by jahirxtrap** [comment]
The error occurs with KubeJS.
KubeJS-Mods/KubeJS#878

**Comment by jahirxtrap** [comment]
Fixed in 1.3.5
